### ISSUE TITLE
Request for Example Scripts and Test Data

### ISSUE THREAD

**Issue by devsecops4f** [NetManAIOps/Chain-of-Event#1]
Hi there,

Could you provide some example scripts to run the code? Any test data you can share would also be really helpful.

Thanks!

**Comment by yaozh16** [comment]
@devsecops4f Thank you for your interest in our work. Our data is currently under review by eBay, and once the review process is completed, we will add it to the repository.
Thanks for your understanding!

**Comment by chowkamlee81** [comment]
@yaozh16 do you have update on Example Scripts and Test Data?
